apiVersion: v1
kind: Service
metadata:
  name: echoserver
  annotations:
    environment: production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver