pipeline:
  test:
    image: ruby:2.4
    commands:
      - bundle install --path bundler
      - bundle exec rspec spec/ # && bundle exec rubocop --fail-level A -S --format c --parallel
  docker_latest:
    registry: quay.io
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/mortar
    dockerfile: Dockerfile
    auto_tag: true
    when:
      branch: ['master']
      event: ['push']
  docker_release:
    registry: quay.io
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/mortar
    dockerfile: Dockerfile
    auto_tag: true
    when:
      event: ['tag']

  release-gem:
    image: ruby:2.4
    secrets: [ rubygems_auth ]
    commands:
      - mkdir -p ~/.gem
      - echo $RUBYGEMS_AUTH | base64 -d > ~/.gem/credentials && chmod 0600 ~/.gem/credentials
      - gem build kontena-mortar.gemspec
      - gem push *.gem
    when:
      event: ['tag']

  create_gh_release:
    image: ubuntu:xenial
    secrets: [ github_token ]
    commands:
      - ./build/drone/create_release.sh
    when:
      event: tag
  build_xenial:
    image: ubuntu:xenial
    secrets: [ github_token ]
    environment:
      - CPPFLAGS=-P
    commands:
      - ./build/drone/ubuntu_xenial.sh
    when:
      event: tag
