language: ruby
sudo: required
cache: bundler
bundler_args: --without development
env:
  global:
    - secure: "sHsJok4nQFsowb0KOGdati/aXUb0Nz46QAoioSyM24OT8Hb2ltyUpJpjZ78Oehfh+pxlQYjCJSCVkNN6gUXf6/z127GVDA6AT1fL+bvwb6DrrWUOE89ur04EAhU8nyFioI1oaYhHoeRELPkZ7Mns3ItfHt2rGgp+ehc7IPWaaD///GS29aaYWWC/WtWL8X238OmNl9708uzRvvfMHeGYfcH2ztSc5AKJ+qrd80epTIxWDUZtQp9t3FxHQo9nSg+UT6wCiwd05CZ9toGZZGtIL69jcPE1ghZcp36w7bsUxaZozR+dNzx0MPRhNyIfmbJ5nOih79yDJChKlw7meLeWjx5+UNoGmWycpa7aX9YgdFAY8ADs9wv/QQyFPZg38dZGEWVJ80yblJ8Kqb1RwH8CaBgtzuaOHiGNQaFpNshwviNPOsnJQb40u+7LfUi7KfnF4hU+VcDr0ZuDi4/Oo5RQr8Y//KgfTcP7+5gfIlYVt2tOYK1T/Hxj0EBHJdflZHclWN+agiLSODPq9+Yj2+35+0G0ObgUVVvj20BkPl5E8duEg+//cDZhoiBLRsrRryHxAyTznwXevjjvPDn6eU/rWTjVqfVIzDMpFvwnqba7FapGs0EYmwOl4zY4J1CojIKXEMRmOgh2G0wJmMOOPUBuGYmOVs9O6G8k5uTKWJobXuY="
stages:
  - name: publish binary
    if: tag IS present
jobs:
  include:
    - stage: publish binary
      script: ./build/travis/macos.sh
      rvm: 2.4
      os: osx